name: SBOM Generation with Syft and CycloneDX

on:
  release:
    types: [created]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Display sha hash
        run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"
          echo "GitHub Long Commit Hash  : ${github_sha_hash}"
          echo "GitHub Short Commit Hash : ${github_sha_short}"

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Create ~/bin directory
        run: mkdir -p $HOME/bin

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.24.0
        with:
          syft-version: v1.51.1

      - name: Download CycloneDX CLI
        run: |
          curl -sSfL https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.33.1/cyclonedx-linux-x64 \
            -o $HOME/bin/cyclonedx
          echo "bfc8b2538da86fe239bc53658bbb63c1c8c510a293c1e6891aa5bea5d3c58746 $HOME/bin/cyclonedx" | sha256sum -c -
          chmod +x $HOME/bin/cyclonedx

      - name: Add ~/bin to PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Generate SBOM
        run: |
          syft scan . -o cyclonedx-json=sbom.json
          syft scan . -o table

      - name: Validate SBOM
        run: cyclonedx validate --input-file sbom.json

      - name: Upload sbom.json to release
        uses: softprops/action-gh-release@v3.0.2
        with:
          files:
            sbom.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
